### ISSUE TITLE
issue while building tahoe-lafs on Mac

### ISSUE THREAD

**Issue by AlexandreD59** [tahoe-lafs/pycryptopp#21]
One of my friend have tried to run the command python setup.py build. 

This has failed with this issue : 
Running pycryptopp-0.6.0.1206569328141510525648634803928199668821045408958/setup.py -q bdist_egg --dist-dir /var/folders/84/_v0_v08n3gz90wn2_tzpx9d80000gn/T/easy_install-3LD7F7/pycryptopp-0.6.0.1206569328141510525648634803928199668821045408958/egg-dist-tmp-esKjHa
unable to execute clang: No such file or directory
error: Setup script exited with error: command 'clang' failed with exit status 1

After having read the GNUmakefile of the cryptopp it seems there is a fix for clang compiler. 

May you add the fixes that had been commited in this commit : https://github.com/ametaireau/cryptopp/commit/414f67f7b5c0070e9338abbe91d3a3ce5bdee151 ?

**Comment by david415** [comment]
fixed according to https://tahoe-lafs.org/trac/pycryptopp/ticket/97
