### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by frispete** [tahoe-lafs/pycryptopp#36]
Hi,

any chance of gaining Python3 support, soon?

Coming from packaging background, I noticed, that Beaker gained a pycryptopp dependency lately (well, it's somewhat optional, replaceable with pycrypto, while they prefer pycryptopp). 

Cryptography is the very last resort to play games like this, IMHO.

Unfortunately, without Python3 support, this results in a packaging discrepancy.

**Comment by jayvdb** [comment]
It has been removed from openSUSE for this reason https://build.opensuse.org/request/show/657276

And I cant see it in Fedora packages now either.

**Comment by exarkun** [comment]
The Tahoe-LAFS project has decided it is not interested in porting pycryptopp to Python 3.  Instead, Tahoe-LAFS is switching to the "cryptography" library.

I don't have any problem with anyone else taking on this porting effort but I'm closing this to reflect the fact that the maintainers have no plans of taking this on.

**Comment by pmalhaire** [comment]
Hello I am porting this module to python3
I could build all but test are still failing because the package _pycryptotop is not found I guess I did not export it right
https://github.com/pmalhaire/pycryptopp branch python3
