### ISSUE TITLE
strange version of pycryptopp

### ISSUE THREAD

**Issue by catafest** [tahoe-lafs/pycryptopp#40]
Into my Fedora 25 I used this command , see the version of pycryptopp, why ?:

```
[root@localhost myuser]# pip list --outdated --format=freeze
...
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
...
```

**Comment by exarkun** [comment]
This seems to be a legit version.  See https://pypi.org/project/pycryptopp/0.6.0.1206569328141510525648634803928199668821045408958/.
